config/routes.rb
Rails.application.routes.draw do

  get 'passwords/new'

  root 'site#index'

  get '/about', to: 'site#about'

  get '/terms', to: 'site#terms'

  get '/maps', to: 'site#maps'

  # routes for login
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  # routes for signup
  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  #routes for map
  # get '/maps'


  # routes for logout
  post 'session/destroy', to: 'sessions#sdestroy' 

  get "/logout" => "sessions#destroy" #TODO: DELETE THIS BEFORE PRODUCTION

  # # routes for uploading images
  # get '/explore', to: 'images#new'

  # post '/explore', to: 'images#create'

  resources :users

  resources :passwords

  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessor :trash

  validates :trash,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }


  # has_attached_file :trash, styles: {

  #   thumb: '100x100>',
  #   square: '200x200#',
  #   medium: '300x300>'
  # }

  has_attached_file :trash,
  :styles => { :medium => "300x300>", :thumb => "100x100>", :square =>"200x200#"},
  :storage => :s3,
  :bucket => ENV['AWS_BUCKET_NAME'],
  :default_url => '/images/:attachment/missing_:style.png',
  :url =>':s3_domain_url',
  :path => '/:class/:attachment/:id_partition/:style/:filename'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :avatar
  # attr_accessor :avatar_file_name
  
  has_secure_password # for hand written rails oauth
  has_many :posts
  # has_many :images

  validates :first_name, presence: true
  validates :email, presence: true
  
  def set_password_reset
    self.code = SecureRandom.urlsafe_base64
    self.expires_at = 4.hours.from_now
    self.save!
  end

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate,password)
  end
  # validates :avatar,
  #   attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
  #   attachment_size: { less_than: 5.megabytes }

  # has_attached_file :avatar, 
  # styles:{
  #   thumb: '100x100>',
  #   square: '200x200>',
  #   medium: '300x300>'
  # }

# # Validate the attached image is image/jpg, image/png, etc
#   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_authenticated?
    # redirect_to login_url if session[:user_id].nil?
    redirect_to login_url unless current_user
  end

  def current_user
    # use 'current user' if available or find the user by it's id.
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_name
    @user_name = User.find(session[:user_id]) if session[:user_id] != nil
    
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  # GET /friends/new
  def new
    @image = Image.new  
  end

  def create
    # @note = note.new
    # image_hash = {}
    # image_hash[:trash] = trash_to_hash(image_params()[:trash])
    # image_hash[:note] = image_params[:note]
    # #binding.pry
    # ImageUploadWorker.perform_async(image_hash.to_json)
    image = Image.new(image_params)
    if image.save
      redirect_to images_url
    else
      render :new
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  
  private
    
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:trash, :note)
    end

    def trash_to_hash(trash)
      trash_hash = Hash.new
      trash_hash[:content_type] = trash.content_type
      trash_hash[:headers] = trash.headers
      trash_hash[:original_filename] = trash.original_filename
      trash_hash[:tempfile] = trash.tempfile.path
      trash_hash
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])

    if user
      # start password flow
      user.set_password_reset
      UserMailer.password_reset(user).deliver

    end

    # render text: "User has been reset"
    redirect_to login_url, notice: "Email was sent with instructions"

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    #my login form
    # render :new
  end

  def create
    @user = User.authenticate(params[:user][:email], params[:user][:password])

    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), :notice => "User Logged in Successfully!"
    else
      flash.now[:notice] = "Can't log you in"
      render :new
    end

  end

  def destroy
      session[:user_id] = nil
      # render text: "You've destroyed the session"
      redirect_to '/'
  end
  
  def edit

  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index 
    # # @images = UnsavedMsg.new
    # user_name
  end


  def about
    # user_name
    render :about 
  end

  def terms
    render :terms
  end

  def maps
    render :maps
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# skip_before_action :is_authenticated?, only: [:new, :create]

  def index
    redirect_to '/'
    @users = User.all
  end

  def new
    if session[:user_id] == nil
      @user = User.new
    else
      redirect_to user_path(session[:user_id])
    end
  end

  def create
    if session[:user_id] == nil
      user_info = params.require(:user).permit(:email,:first_name, :last_name, :password)
      @user = User.create(user_info)
      if @user.errors.any?
        # puts "no user was created, why?!?"
        flash.now[:notice] = "Can't create a new user! Are you a human?"
        render :new
      else
        # puts "a new user was created"
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), :notice => "You have just logged in!"
      end
    end
  end

  def show
    if session[:user_id] != nil
      if session[:user_id].to_i == params[:id].to_i
        @user = User.find_by_id(params[:id])
      else 
        redirect_to user_path(session[:user_id])
      end
    else
      redirect_to '/'
    end
  end

  def edit
    if session[:user_id] != nil
      if session[:user_id].to_i == params[:id].to_i
        @user = User.find(params[:id])
      else
        redirect_to user_path(session[:user_id])
      end
        # redirect_to edit_user_path(session[:user_id])
    end
  end

  def update
    find_user_id
    @current_user = current_user
    user_info = params.require(:user).permit(:email, :first_name, :last_name,)
    user = User.find_by_id(params[:id])
    user.update_attributes(user_info) if (user)
    redirect_to users_path
  end

  def destroy
    user = User.find_by_id(params[:id])
    user.destroy
    redirect_to users_path
  end

   
  private

  def find_user_id
    user_id = params[:id]
    @user = User.find_by_id(user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<!-- index.html.erb -->

<div class="container">
  <div class="row">
    <div class="col-xs-12">

    <h1>All reported images</h1>
    <hr>
     
<!--   <div > -->
    <% @images.each do |image| %>
    <div class="col-xs-18 col-sm-6 col-md-3">
      <div class="thumbnail">
    <%= image_tag image.trash.url(:square), class: "img-thumbnail"%>
    <div class="caption">
       <h4>Notes:</h4>
                <p><%= image.note %></p>
                 <% if session[:user_id] != nil %>
                <p><a href="#" class="btn btn-info btn-xs" role="button">LikeIt</a> <a href="#" class="btn btn-default btn-xs" role="button">Volunteer</a></p>
                <% end %>
            </div>
          </div>
        </div>
    <% end %>


  </div><br>
  <%= link_to 'Go Back', root_path, class: 'btn btn-default' %>
  <%= link_to 'Upload', new_image_path, class: 'btn btn-default' %><br/>
    </div>
    
</div>
</div>

app/views/images/new.html.erb
<!-- <h1>Images#new</h1> -->
<div class="container">
  <div class="row">
  <div class="col-xs-12">
  <h3>Upload and make a difference</h3>

  <%= form_for(@image, multipart: true) do |f| %>

  <div class="field">
    <%= f.label :PickOne %>
    <%= f.file_field :trash, required:true %><br/>
    <%= f.text_area :note, :rows => "5", :cols => "30" %><br/>
  </div>
  <!-- right column -->
  <div class="span6">
 
    <form class="form-horizontal">
      <fieldset>
 
      <!-- Form Name -->
      <legend>Add Your Place</legend>
 
      <!-- Text input-->
      <div class="control-group">
        <label class="control-label">Your name</label>
        <div class="controls">
          <input id="place_name" name="name" type="text" placeholder="" class="input-xlarge" required="">
          
        </div>
      </div>
 
      <!-- Text input-->
      <div class="control-group">
        <label class="control-label">Location</label>
        <div class="controls">
          <input id="location" name="location" type="text" placeholder="Enter a city, state or zipcode" class="input-xlarge" required="">
          <p class="help-block">This field will be geocoded with Google Maps API</p>
        </div>
      </div>
 
      <!-- Button -->
      <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
          <input type="submit" id="locationBtn" name="locationBtn" class="btn btn-primary" value="Add Location">
        </div>
      </div>

  <div class="actions">
    <%= f.submit 'Upload It'%><br/>
    <%= link_to 'Nevermind', root_path, class: 'button' %><br/>
    <%= link_to 'View all Images', images_path, class: 'button' %>
  </div>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>

<%= @image.trash %> 
<%= image_tag @image.trash.url(:medium) %>

app/views/images/update.html.erb
<h1>Images#update</h1>
<p>Find me in app/views/images/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CleanupCity</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="../favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,800,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
  
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>    <!-- Google Maps API -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>  <!-- Google CDN for jQuery -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  
     <!-- Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,400italic,700,900' rel='stylesheet' type='text/css'>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- // Fonts -->

  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container" id="topContainer">
  <nav class="navbar navbar-default" role="navigation">

    <div class="nav navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="home" href="/"><%= image_tag "cleancitylogosmall.png", id: "logoimg"%>CleanUpCity</a>
    </div>


    <div class="collapse navbar-collapse navbar-right pull-right" id="bs-example-navbar-collapse-1"> 
      <ul class="nav navbar-nav">
    
        <li><a href="/about">About</a></li>
        <li class="divider"></li>
          <% if session[:user_id] == nil %>
            <li><a href="/signup">SignUp</a></li>

           <% elsif session[:user_id] != nil %>
            <li><a href="/logout">Log Out</a></li>
          <% end %>

            <!-- <li><a href="/login">Log In</a></li> -->

            <li class="divider-vertical"></li>
            <li><a href="/images">Explore</a></li>
            <li class="dropdown">
              <% if session[:user_id] == nil %>
               <a href="/login" class="dropdown-toggle" data-toggle="dropdown">Login<span class="caret"></span></a> <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                  <!-- Login form here -->
                  <%= form_for :user, :url => login_path do |f| %>
                  <%= f.text_field :email, placeholder: "Email", class:"form-control" %>
                  <%= f.password_field :password, placeholder: "Password", class:"form-control" %>
                  <%= f.submit "Login", class: "btn btn-xs btn-primary form-control" %><br>
                <h6><%= link_to "Forgot Password?", new_password_path %> </h6>
                <% end %></li>
              <% end %>
            </li>
        </ul>
    </div>
  </nav>
</div>
<!-- <div class="container"> -->
<%= yield %>

  <div class="container">
<hr>
  <div class="footer">
    <p class="pull-right"><a href="#topContainer">Back to top</a></p>
    <p>&copy; 2014 CleanUpCity, Inc. All Rights Reserved,  <a href="/terms">Terms of Use</a></p>
    <p>All community content copyright its respective owner.</p>

  </div>
  
  </div>
<!-- </div> -->

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/shared/_login_form.html.erb
<!-- This button only shows when user is not logged in.
   -->
  <% if session[:user_id] == nil %>
    <a href id="loginModal" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Login
    </a>
  <% end %>

<!-- Login Modal -->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="login-form">
      <div class="modal-header">
        <div class="text-center">
          <%= image_tag "cleancitylogosmall.png" %>
        </div>
      </div>
          <div class="loginmodal-body">
            <div class="form-group">
              
              <br>

                <div class="row">
                  
                  <h2 class="form-group text-center">  </h2>

                  <% flash.each do |k,v| %>
                    <p class "text-danger" id ="<%= k %>"><%= v %></p>
                  <% end %>

                  <%= form_for :user do |f| %>
                    <div class="form-group text-center col-md-offset-2 col-md-8">
                      <%= f.text_field :email, placeholder: "Enter your email", class: "form-control input-sm", autofocus: true  %>
                    </div>
                     
                    <div class="form-group text-center col-md-offset-2 col-md-8">
                      <%= f.password_field :password, placeholder: "Password", class: "form-control input-sm" %>
                    </div>
                      
                    <div class="">
                    <%= f.submit "Login", class: "btn btn-md btn-primary form-group col-md-offset-4 col-md-4" %><br/>
                    </div>
                  <% end %>

            <h5 class="col-md-5"> <%= link_to "Forget Password?", new_password_path, class:"text-center" %> </h5>
            <h5 class="col-md-offset-5  col-md-2"><%= link_to "Go Home", root_url, class:"text-center" %></h5>
                </div>
            </div>

        </div>
    </div>
  </div>
</div>

app/views/site/about.html.erb
<div class="container">
  <div class="row">

    <section class="top">
      <div class="col-md-12 col-md-offset-3 ">
        <div class="row">
          <br>
          <div class="col-md-6">
            <h1 class="text-center">CleanUp City</h1><br>
            <p>
              <strong>About Us</strong><br> 
               Cleanup City is a simple application that helps residents to identify public safety, environmental issues and upload pictures and report them for resolution.<br/>

               <p>A picture tells thousand words and Cleanup City is a collaborative platform that gives an opportunity for residents, neighborhood groups and associations to focus on cleaning, greening and organize events for city clean up.</p>
            </p><br/>
            <p>
              <strong>Mission</strong><br> 
              Cleanup City’s mission is to improve quality of life for residents by investing on communities.<br/>
            </p><br/>
             <p>
              <strong>Objectives</strong><br> 
                  <li>To encourage residents take ownership of their communities.</li>
                  <li>To provide opportunities and organize events  for community improvement activities.</li>
                  <li>To promote leadership for greening, maintenance and environmentally supportive efforts.</li>
                  <li>To report issues and resolution in a timely manner.</li>
            </p>
            <hr class="featurette-divider"/>
            <h3 class="text-center"><strong>Technologies</strong></h3><br>
            <p class="text-center">
              Ruby, Rails, Javascript, Bootstrap(Front-end framework), jQuery, HTML5, CSS3, AWS S3 (for cloud storage) and paperclip, Google maps API.
            </p>
            <hr class='featurette-divider'/>
          <br>

        <div class="row text-center">
          <h3>Developer</h3>
 
            <br>
          <div class="span2">
            <img src="https://avatars2.githubusercontent.com/u/6865075?v=2&s=400"  alt="" class="img-rounded">
          </div>
          <div class="span4">
            <blockquote>
              <p>Sana Nasar</p>
              <small><cite title="Source Title">Full Stack Web Developer.<i class="icon-map-marker"></i></cite></small>
            </blockquote>
          </div>
              <p class="text-center">
                 <div class="span2">
                An energetic and imaginative young web developer who is never tired of trying new things. I love to code and believe programming is profoundly creative.</p>
      <!--     <div class="row col-md-offset-2 col-md-3"> -->
              <h6 class="text-center"><a href="https://github.com/SanaNasar">GitHub</a></h6>
            <h6 class="text-center"><a href="http://www.linkedin.com/in/sananasar">LinkedIn</a></h6>
            <h6 class="text-center"><a href="https://twitter.com/SanaNasar_">Twitter</a></h6>
          </div>
         </div>

        </div>
            
          </div>
</div>
          

            
          



            

app/views/site/index.html.erb
<div class="jumbotron" id="topbackground">

<div class="container">
<div class="row">

<div class="col-xs-4 text-center">
<%= image_tag "cleancitylogo3.png", id: "jumboimg", class: "img-responsive"%>
</div>

<div class="col-xs-8"> 

<h2 id="tag">Working together to keep city clean</h2>
<p>Investing on communities... Investing happiness</p>
</div>

</div>  <!-- row close -->

</div>  <!-- container close -->
</div>

<div class="row">
    <div class="text-center" id="middle-section">

      <div class="goal"><blockquote class="text-center">"Our mission is to invest on communities to improve quality of life for people by cleaning and greening the city"</blockquote></div >
  
    </div>
</div>

<!-- 1/3 Home PAGE ENDS -->
<div class="text-center" id="learn-more">
<a href="#bottomContainer" class="scroll">Explore<i class="fa fa-sort-desc fa-2x"></i></a>
</div><br>

<!-- 2/3 HOME PAGE BEGINS  -->
<div id="middle"><br/>
    <div class="goal"><blockquote class="text-center">Upload from wherever you are...</p></div>
      <div class="middle_images">
      <div class="grid">

        <figure class="effect-layla">
            <%= image_tag "ccpic5.jpg", class: "img-responsive" %>
          <figcaption>
            <h2>Crazy <span>Layla</span></h2>
            <p>Reported On: 09/24/2014 @ 06:13 PM
              Reported By: Citizen24766
              Notes:(Additional info!) </p>
          </figcaption>     
        </figure>
        <figure class="effect-zoe">
           <%= image_tag "ccpic2.jpg", class: "img-responsive" %>
          <figcaption>
            <h2>Creative <span>Zoe</span></h2>
            <span class="icon-heart"></span>
            <span class="icon-eye"></span>
            <span class="icon-paper-clip"></span>
            <p>Reported On: 09/05/2014 @ 12:13 PM
              Reported By: CreativeZo1234
              Additional Info: "The walls are need to be painted"</p>
          </figcaption>     
        </figure>
     <figure class="effect-oscar">
          <%= image_tag "ccpic8.jpg", class: "img-responsive" %>
          <figcaption>
            <h2>Warm <span>Oscar</span></h2>
            <p class="Text-center">Reported On: 09/01/2014 @ 02:13 PM
              Reported By: WOscar2342
              Additional Info: "Interesting issue to be solved"</p>
          </figcaption>     
        </figure>
<!-- 2/3 HOME PAGE ENDS -->

<br><br>
<h3 class="text-center">Make A Difference</h3>
<br>


<!-- 3/3  PAGE BEGINS -->
 <div class="container" id="bottomContainer" >
  <div class="row">
    <div class="stepOne col-md-4 text-center">
      <%= image_tag "signup.jpg", id: "tutorial", class: "img-circle", style: "height:250px; width:250px" %>
      <h3 class="tut_desc"><a href="/signup" class="btn btn-lg btn-primary" id="signup">Sign Up</a></h3>
    </div>
    <div class="stepTwo col-md-4 text-center">
      <%= image_tag "report.jpg", id: "tutorial", class: "img-circle", style: "height:250px; width:250px" %>
      <h3 class="tut_desc"><a href="images/new" class="btn btn-lg btn-primary" id="upload">Upload</a></h3>
    </div>
    <div class="stepThree col-md-4 text-center">    
      <%= image_tag "map.jpg", id: "tutorial", class: "img-circle", style: "height:250px; width:250px" %>
      <h3 class="tut_desc"><a href="/maps" class="btn btn-lg btn-primary" id="map">Map</a></h3>
    </div>
  </div> <!-- row close -->
</div> <!-- container close -->
<!-- 
3/3 PAGE ENDS -->
<br/><br/>
</div>


 

app/views/site/maps.html.erb
 <!-- Dislay Google map here -->
<div class="container">
  <div class="row">
    <div id='map-canvas', style= "width: 800px; height: 600px" ></div><br/>
  <div>
  <div class="row">
    <div class="text-center">
    <label for="address"> Address:</label>
    <input type="text" id="address"/>
    <button class="btn btn-md btn-primary" id="locate">Locate</button>
    </div>
  </div>
  
  </div>
</div>
</div>

app/views/site/terms.html.erb
<div class="container">

    <section class="top">
      <div class="col-md-12 col-md-offset-3 ">
        <div class="row">
          <br>
          <div class="col-md-6">
            <h1 class="text-center">Basic Terms</h1><br>
            <li>You must be 13 years and older to use this site.</li>
            <li>You are responsible for any activity that occurs under your screen name.</li>
            <li>You are responsible for keeping your password secure.</li>
            <li>You must not abuse, harass, threaten, invade the privacy of, or intimidate other CleanupCity members.</li>
            <li>Upload relevant stuff and you are responsible for the stuff you upload it.</li>
          </div>
        </div>
      </div>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/delete.html.erb
<h1>Tags#delete</h1>
<p>Find me in app/views/tags/delete.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>

app/views/users/edit.html.erb
<!-- edit user info page -->
<div class="container">
  <h1 class="subtitle text-center"> <h1>Edit Your Profile </h1> 
  <div class="form">

  <% user_path @user %>

  <div class="col-md-4 col-md-offset-4">

    <%= form_for @user do |f| %>

      <%= f.text_field :first_name, placeholder: @user.first_name, class: "form-control"%><br>
      <%= f.text_field :last_name, placeholder: @user.last_name, class: "form-control"%><br>
      <%= f.text_field :email, placeholder: @user.email, class: "form-control"%><br>
      <%= f.submit "Update profile", class: "btn form-control btn-success" %>

    <% end %>

  </div>
</div>
</div>

app/views/users/index.html.erb
index.html.erb

app/views/users/new.html.erb
<!-- Sign Up Modal -->
<div class="container">

  <%flash.each do |k,v|%>
    <h2 id="<%=k%>"><%=v%> </h2>
    <% end %>

  <%=form_for @user do |f| %>

    <div class="col-md-4 col-md-offset-4">
      <p></p>

        <%= f.text_field :first_name, required:true, autofocus:true, placeholder: "first name", class: "form-control"%><br>
        <%= f.text_field :last_name, placeholder: "last name", class: "form-control"%><br>
        <%= f.text_field :email, required:true, placeholder: "enter email", class: "form-control"%><br>
        
        <%= f.password_field :password, placeholder: "Password", class: "form-control"%><br>
        <%= f.password_field :password_confirmation, placeholder: "confirm password", class: "form-control" %><br>

    
          <%= f.submit "Sign Up", class: "btn form-control btn-primary" %>
          <% end %>
         
        <span class="pull-right"><a href="/">Go home</a></span>
        <span class="pull-left"><a href="/login">Login</a></span>
    </div>


  </div>
</div>

app/views/users/show.html.erb
<!-- user - show.html.erb -->
<!-- user home page
 -->
<div class="container">
  <%= form_for @user do |f| %>
    <h3 style="margin: -3px;">
      <%= f.label :first_name, "Welcome #{@user.first_name} to your homepage" %></br>

    <h3 style="margin: -3px;">
    <%= f.label :email, "#{@user.email}" %></br>

    <% if @current_user and @user.id == @current_user.id %>
      <h3> Write something here!</h3>
  </br></br>
    <% end %>

    <h3>Ready to make a difference???</h3>

    <div class="col-md-2">
      <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-success" %>
    </div>
       <div class="col-md-2">
      <%= link_to "View Images", images_path, class: "btn btn-success" %>
    </div>

  <% end %>
</div>